name : Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    - runs-on: ubuntu-latest


  steps:
    - name: Checkout Repository
      users: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.13"

    - name: Install dependencies
      run:
        pip install -r requirements.txt

    - name: Archive Project
      run: zip project.zip .




